---
- name: Install apache
  apt: name={{ item }} state=present
  with_items:
   - apache2

- name: Install site config
  template: src=templates/example.conf.j2 dest=/etc/apache2/sites-available/{{ apache.server_name|lower|replace('.', '_') }}.conf

- name: Disable default site
  command: a2dissite *default*

- name: a2ensite {{ apache.server_name }}
  command: a2ensite {{ apache.server_name|lower|replace('.', '_') }}
  args:
    creates: /etc/apache2/sites-enabled/{{ apache.server_name|lower|replace('.', '_') }}.conf
  notify:
    - restart apache2

- name: apache service state
  service: name=apache2 state=started enabled=yes