- hosts: laravel
  become: true
  vars_files:
    - vars/setup.yml
    - vars/php.yml
    - vars/apache.yml
    - vars/repository.yml
    - vars/laravel.yml
  roles:
    - { role: setup }
    - { role: fail2ban }
    - { role: force_xterm_bash }
    - { role: unattended_upgrades }

    - { role: mysql-server }
    - { role: php }
    - { role: apache }
    - { role: nodejs }
    - { role: composer }

    - { role: repository_pull }
    - { role: laravel }
