---
- name: Install MySQL and related packages
  apt:
    name: "{{ item }}"
  with_items:
    - python-mysqldb
    - mariadb-server

- name: Check if there is already a mysql root password stored
  become: true
  stat: path=/root/.my.cnf
  register: password_set

- name: Generate mysql password
  set_fact: 
    mysql_root_password: "{{ lookup('password', '/tmp/passwordfile chars=ascii_letters,digits') }}"
  when: not password_set.stat.exists

- name: Enable easy root mysql login
  become: true
  template: src=templates/my.cnf.j2 dest=/root/.my.cnf owner=root group=root mode=0600
  when: not password_set.stat.exists

- name: Start the MySQL service
  become: true
  service:
    name: mysql
    state: started
    enabled: true
  when: not password_set.stat.exists

- name: update mysql root password for all root accounts
  become: true
  mysql_user: 
    name: root 
    host: "{{ item }}" 
    password: "{{ mysql_root_password }}"
    check_implicit_admin: yes
    priv: "*.*:ALL,GRANT"
  with_items:
    - "{{ ansible_hostname }}"
    - 127.0.0.1
    - ::1
    - localhost
  when: not password_set.stat.exists